name: serenity
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  audio_session: ^0.1.6+1
  cupertino_icons: ^1.0.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^2.1.0
  gradient_widgets: ^0.6.0
  just_audio: ^0.9.12
  rxdart: ^0.27.2
  sliding_up_panel: ^2.0.0+1
  stacked: ^2.2.5
  stacked_services: ^0.8.13

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner:
  stacked_generator:

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
