// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaW3kpZUS_MdfZ0bA3YbzcEqaVLF1pHBs',
    appId: '1:278778488318:web:50a08dfaa4a4c823020caf',
    messagingSenderId: '278778488318',
    projectId: 'thesisgradua',
    authDomain: 'thesisgradua.firebaseapp.com',
    storageBucket: 'thesisgradua.appspot.com',
    measurementId: 'G-YZXFGQNW4R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuxOVMsNnQ6SaECboT2jqStSDA0-B1uwU',
    appId: '1:278778488318:android:9c8911c321d64e87020caf',
    messagingSenderId: '278778488318',
    projectId: 'thesisgradua',
    storageBucket: 'thesisgradua.appspot.com',
  );
}
